### ISSUE TITLE
error in reading multi-line subtitle

### ISSUE THREAD

**Issue by jhdeov** [patrickschu/textgrid-convert#43]
If the SRT has the prose be multiple lines, the SRTparser fails and misinterprets the time stamp. For example, an SRT with:
```
139
00:07:06,467 --> 00:07:08,847
After that, I studied Armenian Studies .

140
00:07:08,847 --> 00:07:12,957
In university? 
Hamazkayin had opened

141
00:07:12,957 --> 00:07:16,827
their own Armenian Studies department.

```

The extra line "Hamazkayin" Causes the parser to read the number 141 as a timestamp. 

`start, end = timestamps.split(time_stamp_sep)
ValueError: not enough values to unpack (expected 2, got 1)`

I have to manually change the newlines into a single line.

**Comment by patrickschu** [comment]
Thanks @jhdeov for filing the detailed report

- I will look into this over the week
- If you are able to share a file that errors out in this way, that would be cool as well (will add it to tests)

**Comment by jhdeov** [comment]
There's this other python [script](https://github.com/jhdeov/SrtToTextgrid/blob/master/SrtToTextgrid.py) that doesn't have this multi-line problem. I don't know if you can 'copy' parts of their code for this error. 
For the file, the excerpt was from this public [SRT](https://amara.org/hy/videos/nGqPPtKWkbL1/en/2539488/10730534/).

**Comment by patrickschu** [comment]
Issue is with `parse_transcription()`function in [textgrid_convert/srtParser.py:29](https://github.com/patrickschu/textgrid-convert/blob/b7d43d62b1243b5e9b30854dd476b80b56484c29/textgrid_convert/srtParser.py#L29).

- Fix: Add text cleaner function to init

**Comment by patrickschu** [comment]
Hi @jhdeov 
I fixed this issue, see PR #46 

Can you try `pip install textgrid-convert==0.4.3` and see if things work now? Thanks!

**Comment by jhdeov** [comment]
@patrickschu  I have general pip problems so I relied on just the github source code. It looks like release 4.3 isn't online yet? But if the files/snippets from the above comments work on your side, then I believe it :)

**Comment by patrickschu** [comment]
Hi @jhdeov Ah I see - yes I used your sample files in the unit tests

- The GH has not been updated/tagged to the new version as stuff came up
- I will do so later today. 
Have a good Friday
