### ISSUE TITLE
Error: No such module exists

### ISSUE THREAD

**Issue by mshakirDr** [patrickschu/textgrid-convert#49]
Operating system: Windows 10, Windows subsystem for linux (Ubuntu)
This package when installed from Pypi.org is successfully installed but it cannot be imported. The commandline version does not work as well. It always throws the error that the module were not found.
The second issue is that they appears to be a discrepancy in version number (the version number on Pypi.org is 0.44 but the one shown here appears to be 0.3 something).

**Comment by patrickschu** [comment]
Thanks for filing @mshakirDr , and sorry about the delay

- The versions 0.4.1 - 0.4.4 were indeed broken on PyPi, apologies
- I pushed a new version 0.4.9, which works on my end (Ubuntu)

Let me know if any other issues observed

![gh_fix](https://user-images.githubusercontent.com/11368605/236716339-da2f7c52-8e71-4f6a-bf7e-6018b154a96a.png)
