### ISSUE TITLE
Error:  No module named textgrid_convert

### ISSUE THREAD

**Issue by krolickik** [patrickschu/textgrid-convert#50]
Hi!
I tried installing textgrid_convert on MacOS and Windows 11 and while the installation seems to run fine, I always get the message that the module doesn't exist. Could you suggest any solution to that?

I've seen the closed issue which looks the same and I tried running the same commands but it doesn't help.

**Comment by patrickschu** [comment]
Thanks @krolickik  - I can replicate this on my end, and looking into it. Sorry about any inconveniences!


3.10.9
```
virtualenv issue50env
source issue50env/bin/activate
pip install textgrid-convert
```

Maybe related to #49

**Comment by patrickschu** [comment]
Hi @krolickik 
I pushed a new version (1.0.0) to pypi, so installing from there or pulling the latest master from Github should resolve the issue. Everything works on my end, let me know if not for you.

Thanks for filing the ticket!

<img width="687" alt="Screen Shot 2023-09-24 at 9 10 39 PM" src="https://github.com/patrickschu/textgrid-convert/assets/11368605/64388c08-c5f3-4a8b-9734-a5c3e76675a7">
<img width="812" alt="Screen Shot 2023-09-24 at 9 11 47 PM" src="https://github.com/patrickschu/textgrid-convert/assets/11368605/9c6bb1fd-97a7-447c-a472-722c55557b42">
